all: true
include:
  - 'src/'
exclude:
  - 'src/polyfills'
  - '**/*-fuzz.js'
  - '**/*.d.ts'
clean: true
temp-directory: 'coverage'
report-dir: 'coverage'
skip-full: true
reporter: [json, html, text]
check-coverage: true
branches: 100
lines: 100
functions: 100
statements: 100
