all: true
include:
  - 'src/'
exclude:
  - 'src/polyfills'
  - '**/*-benchmark.js'
  - '**/*.d.ts'
  - 'src/validation/rules/ExecutableDefinitions.js'
  - 'src/validation/rules/LoneSchemaDefinition.js'
  - 'src/validation/rules/PossibleTypeExtensions.js'
  - 'src/validation/rules/UniqueDirectiveNames.js'
  - 'src/validation/rules/UniqueEnumValueNames.js'
  - 'src/validation/rules/UniqueFieldDefinitionNames.js'
  - 'src/validation/rules/UniqueTypeNames.js'
  - 'src/validation/rules/UniqueOperationTypes.js'
clean: true
temp-directory: 'coverage/tests'
report-dir: 'coverage/tests'
skip-full: true
reporter: [json, html, text]
