'use strict';
// Note: This file is autogenerated using "resources/gen-version.js" script and
// automatically updated by "npm version" command.
Object.defineProperty(exports, '__esModule', { value: true });
exports.versionInfo = exports.version = void 0;
/**
 * A string containing the version of the GraphQL.js library
 */
exports.version = '17.0.0-alpha.3';
/**
 * An object containing the components of the GraphQL.js version string
 */
exports.versionInfo = Object.freeze({
  major: 17,
  minor: 0,
  patch: 0,
  preReleaseTag: 'alpha.3',
});
