"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.mapValue = mapValue;

var _objectEntries = require("../polyfills/objectEntries.js");

/**
 * Creates an object map with the same keys as `map` and values generated by
 * running each value of `map` thru `fn`.
 */
function mapValue(map, fn) {
  const result = Object.create(null);

  for (const [key, value] of (0, _objectEntries.objectEntries)(map)) {
    result[key] = fn(value, key);
  }

  return result;
}
