const meta = {
  index: '',
  '-- 1': {
    type: 'separator',
    title: 'Getting Started',
  },
  'getting-started': '',
  'running-an-express-graphql-server': '',
  'graphql-http': {
    display: 'hidden',
  },
  'migrating-from-express-graphql': '',
  'graphql-clients': '',
  'authentication-and-express-middleware': '',
  '-- 2': {
    type: 'separator',
    title: 'Core Concepts',
  },
  'basic-types': '',
  'passing-arguments': '',
  'object-types': '',
  'mutations-and-input-types': '',
  nullability: '',
  'abstract-types': '',
  'custom-scalars': '',
  'constructing-types': '',
  'oneof-input-objects': '',
  'schema-coordinates': '',
  'schema-evolution': '',
  subscriptions: '',
  '-- 3': {
    type: 'separator',
    title: 'Experimental Specification Features',
  },
  'experimental-specification-features': '',
  'defer-stream': '',
  'fragment-arguments': '',
  'disabling-error-propagation': '',
  '-- 4': {
    type: 'separator',
    title: 'GraphQL.js Runtime Features',
  },
  'graphql-harness': '',
  'advanced-execution-pipelines': '',
  'abort-signals': '',
  'execution-hooks': '',
  'tracing-channels': '',
  '-- 5': {
    type: 'separator',
    title: 'Advanced Guides',
  },
  'type-generation': '',
  'cursor-based-pagination': '',
  'advanced-custom-scalars': '',
  'operation-complexity-controls': '',
  'n1-dataloader': '',
  'caching-strategies': '',
  'resolver-anatomy': '',
  'graphql-errors': '',
  'using-directives': '',
  'directives-on-directives': '',
  'authorization-strategies': '',
  '-- 6': {
    type: 'separator',
    title: 'Testing',
  },
  'testing-graphql-servers': '',
  'testing-approaches': '',
  'testing-operations': '',
  'testing-resolvers': '',
  'testing-best-practices': '',
  '-- 7': {
    type: 'separator',
    title: 'Production & Scaling',
  },
  'development-mode': '',
  'going-to-production': '',
  'scaling-graphql': '',
};

export default meta;
