import type { ObjMap } from './ObjMap';
/**
 * Creates an object map with the same keys as `map` and values generated by
 * running each value of `map` thru `fn`.
 */
export function mapValue<T, V>(
  map: ObjMap<T>,
  fn: (value: T, key: string) => V,
): ObjMap<V>;
