name: Canary Release

on:
  pull_request:
    branches:
      - main

env:
  NODE_VERSION_USED_FOR_DEVELOPMENT: 17
jobs:
  publish-canary:
    name: Publish Canary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: ${{ env.NODE_VERSION_USED_FOR_DEVELOPMENT }}

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Setup NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Release Canary
        id: canary
        uses: 'kamilkisiela/release-canary@master'
        with:
          npm-token: ${{ secrets.NODE_AUTH_TOKEN }}
          npm-script: 'npm run release:canary'
          changesets: true

      - name: Publish a message
        if: steps.canary.outputs.released
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are available as alpha in npm (based on the declared `changesets`):
            ```
            ${{ steps.canary.outputs.changesetsPublishedPackages}}
            ```
          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish a empty message
        if: steps.canary.outputs.released == 'false'
        uses: 'kamilkisiela/pr-comment@master'
        with:
          message: |
            The latest changes of this PR are not available as alpha, since there are no linked `changesets` for this PR.
          bot-token: ${{ secrets.GH_API_TOKEN }}
          bot: 'theguild-bot'
          github-token: ${{ secrets.GITHUB_TOKEN }}
