name: Push
on: push
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  deploy-to-npm-branch:
    name: Deploy to `npm` branch
    needs: ci
    if: github.ref == 'refs/heads/main'
    environment:
      name: npm-branch
      url: https://github.com/graphql/graphql-js/tree/npm
    uses: ./.github/workflows/deploy-artifact-as-branch.yml
    with:
      artifact_name: npmDist
      target_branch: npm
      commit_message: "Deploy ${{github.event.workflow_run.head_sha}} to 'npm' branch"

  deploy-to-deno-branch:
    name: Deploy to `deno` branch
    needs: ci
    if: github.ref == 'refs/heads/main'
    environment:
      name: deno-branch
      url: https://github.com/graphql/graphql-js/tree/deno
    uses: ./.github/workflows/deploy-artifact-as-branch.yml
    with:
      artifact_name: denoDist
      target_branch: deno
      commit_message: "Deploy ${{github.event.workflow_run.head_sha}} to 'deno' branch"
